GET http://localhost:3000

###
GET http://localhost:3000/tags

###
GET http://localhost:3000/categories

###
GET http://localhost:3000/ads

### Utilisation de req.query
GET http://localhost:3000/ads?categoryId=1

### Utilisation de req.params
GET http://localhost:3000/ads/2

###
DELETE http://localhost:3000/ads/2

### Utilisation de req.body
POST http://localhost:3000/ads
Content-Type: application/json

{
		"title":"Toto",
		"description":"Lorem ipsum",
		"owner":"Loic",
		"price":42,
		"createdAt":"maintenant",
		"picture":"https://imgur.com",
		"location":"Lille"
}

###
POST http://localhost:3000/tags
Content-Type: application/json

{
		"name":"Toto"
}

###
POST http://localhost:3000/categories
Content-Type: application/json

{
		"name":"misc."
}
